<?php
include('config.php');

echo "<tr>"
echo "<td data-th=\"Product\">"
echo "<div class=\"row\">"
echo "<div class=\"col-sm-3 hidden-xs\"><img src=\"http://placehold.it/100x100\" alt=\"...\" class=\"img-responsive\"/></div>"
echo "<div class=\"col-sm-9\">"
echo "<h4 class=\"nomargin\">Product 1</h4>"
echo "<p>Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet.</p>"
echo "</div>"
echo "</div>"
echo "</td>"
echo "<td data-th=\"Price\">$1.99</td>"
echo "<td data-th=\"Quantity\">"
echo "<input type=\"number\" class=\"form-control text-center\" value=\"1\">"
echo "</td>"
echo "<td data-th=\"Subtotal\" class=\"text-center\">1.99</td>"
echo "<td class=\"actions\" data-th=\"\">"
echo "<button class=\"btn btn-info btn-sm\"><i class=\"fa fa-refresh\"></i></button>"
echo "<button class=\"btn btn-danger btn-sm\"><i class=\"fa fa-trash-o\"></i></button>"
echo "</td>"
echo "</tr>"
echo "</tbody>"
echo "<tfoot>"
echo "<tr class=\"visible-xs\">"
echo "<td class=\"text-center\"><strong>Total 1.99</strong></td>"
echo "</tr>"

?>
